twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    date:
        timezone: America/Vancouver
        format: Y-m-d g:i:s A
        interval_format: '%%d days'
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - "@NinesUtil/form/fields.html.twig"
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'jquery.collection.html.twig'
    globals:
        text_service: '@Nines\UtilBundle\Services\Text'
        image_manager: '@Nines\MediaBundle\Service\ImageManager'
        link_manager: '@Nines\MediaBundle\Service\LinkManager'
        piwik_enabled: '%dhil.piwik_enabled%'
        piwik_url: '%dhil.piwik_url%'
        piwik_siteid: '%dhil.piwik_siteid%'
        piwik_domain: '%dhil.piwik_domain%'
        nines_editor_config: js/editor-config.js
        date_format: Y-m-d
