monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            channels: ["!event", "!doctrine", "!console", "!translation"]
            max_files: 30
